config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
   devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  
  devise_scope :user do
    post '/users/create', to: 'users#create', as: :create_user
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "blogs#index"
  resources :roles
  resources :blogs
  resources :users
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  validates :blog_name, presence: true, length: { minimum: 3 }
  has_rich_text :content
  has_one_attached :image
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    if current_user.role.role_name == "admin"
      @blogs = Blog.all
    else
     @blogs = current_user.blogs
    end
  end
 
  def show
      @blog = Blog.find(params[:id])
  end
 
  def new
    @blog = current_user.blogs.build
  end
 
  def edit
    @blog = Blog.find(params[:id])
    @user = @blog.user
      if (current_user.role.role_name == "admin" || @user == current_user)
        render 'edit'
      else
        flash[:alert] = "This blog is not available for you."
        redirect_to blogs_path
      end
  end
 
  def create
    @blog = current_user.blogs.build(blog_params)
    @blog.image.attach(params[:blog][:image])
 
    if @blog.save
      flash[:notice] = "This blog is successfully created."
      redirect_to @blog
    else
      render 'new'
    end
  end
 
  def update
    @blog = Blog.find(params[:id])
 
    if @blog.update(blog_params)
      flash[:notice] = "This blog is successfully updated."
      redirect_to @blog
    else
      render 'edit'
    end
  end
 
  def destroy
    @blog = Blog.find(params[:id])
    @user = @blog.user
     if (current_user.role.role_name == "admin" || @user == current_user)
        @blog.destroy
        flash[:alert] = "This blog is successfully destroyed."
      else
        redirect_to blogs_path
        flash[:alert] = "This blog is not available for you."
      end   
    redirect_to blogs_path
  end

 
  private
    def blog_params
      params.require(:blog).permit(:blog_name, :description, :content, :image)
    end
  
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def convert_created_date(blog)
    if current_user.timezone == "(GMT+05:30) Kolkata"
      blog.created_at.in_time_zone('Chennai') 
    else
      blog.created_at
    end
  end

  def convert_updated_date(blog)
  	 if current_user.timezone == "(GMT+05:30) Kolkata"
      blog.updated_at.in_time_zone('Chennai') 
    else
      blog.updated_at
    end
  end
end

app/views/blogs/_form.html.erb
<%= form_with model: @blog, class:"form-validate-jquery", local: true do |form| %>

<div>
<%= form.label :blog_name, class:"me-4" %>
<%= form.text_field :blog_name, required: true, placeholder: "Enter blog name", class:"mb-2" %>
<% @blog.errors.full_messages_for(:blog_name).each do |message| %>
      <div><%= message %></div>
<% end %>
</div>

<div>
<%= form.label :description, class:"me-4" %>
<%= form.text_field :description, placeholder: "Enter description", class:"mb-2" %>
<% @blog.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
<% end %>
</div>

 <div class="field">
   <%= form.label :content, class:"mb-2" %>
   <%= form.rich_text_area :content %>
</div>

<div>
<%= form.label :image, class:"mb-2 me-2" %>
<%= form.file_field :image, class:"mt-2" %>
</div>

<div>
  <%= form.submit"Create blog", class:"btn btn-primary mt-2 mb-2" %>
</div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Edit Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path, class:"btn btn-success" %>

app/views/blogs/index.html.erb
<div class="content">
<div class="card">
  <div class="card-header">
    <h5 class="mb-0">Blogs</h5>
  </div>
<table class="table datatable-basic">
 <thead>
  <tr>
    <th>Blog name</th>
    <th>Description</th>
    <th>User email</th>
    <th>Created at</th>
    <th class="text-center">Actions</th>
  </tr>
 </thead>

 <tbody>
  <% @blogs.each do |blog| %>
   <tr>
     <td><%= blog.blog_name %></td>
     <td><%= blog.description %></td>
     <td><%= blog.user.email %></td>
     <td>
      <%= convert_created_date(blog) %>
     </td>
     <td class="text-center">
        <div class="d-inline-flex">
          <div class="dropdown">
            <a href="#" class="text-body" data-bs-toggle="dropdown">
              <i class="ph-list"></i>
            </a>

     <div class="dropdown-menu dropdown-menu-end">
          <%= link_to 'Show', blog_path(blog), class:"dropdown-item" %>           

          <%= link_to 'Edit', edit_blog_path(blog), class:"dropdown-item" %>                
      
          <%= link_to 'Destroy', blog_path(blog), class:"dropdown-item",
          data: { confirm: "Are you sure?", method: :delete, turbo_confirm: "Are you sure?", turbo_method: :delete }
           %>                 
        
      </div>  
    </div>
  </div>
    </td>
   </tr>
  <% end %>
 </tbody>
</table>
</div>
</div>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path, class:"btn btn-success" %>

app/views/blogs/show.html.erb
<body>
<strong class="fs-5 me-2">Blog name:</strong>
<%= @blog.blog_name %></br>

<strong class="fs-5 me-2">Description:</strong>
<%= @blog.description %></br>

<strong class="fs-5 me-2">Content:</strong>
<%= @blog.content %>

<strong class="fs-5 me-2">Image:</strong>
<% if @blog.image.attached? %>
 <image src="<%=(url_for(@blog.image))%>", width="250", height="150">
<% end %></br>

<strong class="fs-5 me-2">Created at:</strong>
<%= convert_created_date(@blog) %></br>

<strong class="fs-5 me-2">Updated at:</strong>
<%= convert_updated_date(@blog) %></br>

<%= link_to 'Edit', edit_blog_path(@blog), class:"btn btn-warning" %>
<%= link_to 'Back', blogs_path, class:"btn btn-success ms-4" %>
</body>