config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
   devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  
  devise_scope :user do
    post '/users/create', to: 'users#create', as: :create_user
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "blogs#index"
  resources :roles
  resources :blogs
  resources :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable 

  belongs_to :role
  has_many :blogs, dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  layout "sign_in"
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  layout "sign_in"
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  layout "sign_in"
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  layout "sign_in"
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout "sign_in"
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  layout "sign_in"
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "user"
  def index
   @users = User.all
  end
 
  def show
    @user = User.find(params[:id])
  end
 
  def new
    @user = User.new
  end
 
  def edit
    @user = User.find(params[:id])
  end
 
  def create
    @user = User.new(user_params)
 
    if @user.save
      puts "===== user created ===== #{@user.inspect} ====="
      UserNotificationMailer.create_user(@user).deliver_now
      redirect_to @user
    else
      puts "===== user errors ===== #{@user.errors.full_messages} ====="
      render 'new'
    end
  end
 
  def update
    @user = User.find(params[:id])
 
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end
 
  def destroy
    @user = User.find(params[:id])
    @user.destroy
 
    redirect_to users_path
  end
 
  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :role_id )
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with model: @user, url: create_user_path, local: true do |form| %>

<div>
<%= form.label :first_name, class:"me-4" %>
<%= form.text_field :first_name, required: true, placeholder: "Enter your first name", class:"mb-2" %>
<% @user.errors.full_messages_for(:first_name).each do |message| %>
      <div><%= message %></div>
<% end %>
</div>

<div>
<%= form.label :last_name, class:"me-4" %>
<%= form.text_field :last_name, placeholder: "Enter your last name", class:"mb-2" %>
<% @user.errors.full_messages_for(:last_name).each do |message| %>
      <div><%= message %></div>
<% end %>
</div>

<div>
<%= form.label :role_name, class:"me-4" %>      
<%= form.collection_select :role_id, Role.all, :id, :role_name, {:selected => 2}, class:"mb-2" %>
</div>

<div>
<%= form.label :email, class:"me-4" %>
<%= form.email_field :email, placeholder: "Enter your email", class:"mb-2" %>
<% @user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
<% end %>
</div>

<div>
<%= form.label :password, class:"me-4" %>
<%= form.password_field :password, placeholder: "Enter your password", class:"mb-2" %>
<% @user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
<% end %>
</div>

<div>
<%= form.label :password_confirmation, class:"me-4" %>
<%= form.password_field :password_confirmation, placeholder: "Enter your password again", class:"mb-2" %>
<% @user.errors.full_messages_for(:password_confirmation).each do |message| %>
      <div><%= message %></div>
<% end %>
</div>


<div>
  <%= form.submit"Create user", class:"btn btn-primary mt-2 mb-2" %>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path, class:"btn btn-success" %>

app/views/users/index.html.erb
  <div class="card-header">
    <h5 class="mb-0">Users</h5>
  </div>
<table class="table datatable-basic">
 <thead>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>User email</th>
     <th class="text-center" >Actions</th>
  </tr>
 </thead>

 <tbody>
  <% @users.each do |user| %>
   <tr>
     <td><%= user.first_name %></td>
     <td><%= user.last_name %></td>
     <td><%= user.email %></td>
     <td class="text-center">
        <div class="d-inline-flex"> 
          <div class="dropdown">
            <a href="#" class="text-body" data-bs-toggle="dropdown">
              <i class="ph-list"></i>
            </a>

     <div class="dropdown-menu dropdown-menu-end">
          <%= link_to 'Show', user_path(user), class:"dropdown-item" %>           

          <%= link_to 'Edit', edit_user_path(user), class:"dropdown-item" %>                
      
          <%= link_to 'Destroy', user_path(user), class:"dropdown-item",
          data: { confirm: "Are you sure?",method: :delete, turbo_confirm: "Are you sure?", turbo_method: :delete }
           %>                 
        
      </div>  
    </div>
  </div>
    </td>
   </tr>
  <% end %>
 </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path, class:"btn btn-success" %>

app/views/users/show.html.erb
<body>
<strong class="fs-5 me-2">First name:</strong>
<%= @user.first_name %></br>

<strong class="fs-5 me-2">Last name:</strong>
<%= @user.last_name %></br>

<strong class="fs-5 me-2">Email:</strong>
<%= @user.email %></br>

<strong class="fs-5 me-2">Created at:</strong>
<%= convert_created_date(@user) %></br>

<strong class="fs-5 me-2">Updated at:</strong>
<%= convert_updated_date(@user) %></br>

<%= link_to 'Edit', edit_user_path(@user), class:"btn btn-warning" %>
<%= link_to 'Back', users_path, class:"btn btn-success ms-4" %>
</body>