config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
   devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  
  devise_scope :user do
    post '/users/create', to: 'users#create', as: :create_user
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "blogs#index"
  resources :roles
  resources :blogs
  resources :users
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users, dependent: :destroy
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
   def index
    @roles = Role.all
  end
 
  def show
    @role = Role.find(params[:id])
  end
 
  def new
    @role = Role.new
  end
 
  def edit
    @role = Role.find(params[:id])
  end
 
  def create
    @role = Role.new(role_params)
 
    if @role.save
      redirect_to @role
    else
      render 'new'
    end
  end
 
  def update
    @role = Role.find(params[:id])
 
    if @role.update(role_params)
      redirect_to @role
    else
      render 'edit'
    end
  end
 
  def destroy
    @role = Role.find(params[:id])
    @role.destroy
 
    redirect_to roles_path
  end
 
  private
    def role_params
      params.require(:role).permit(:role_name)
    end
  
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_with model: @role, local: true do |form| %>

<div>
<%= form.label :role_name, class:"me-4" %>
<%= form.text_field :role_name, required: true, class:"mb-2" %>
<% @role.errors.full_messages_for(:role_name).each do |message| %>
      <div><%= message %></div>
<% end %>
</div>

<div>
  <%= form.submit"Create Role", class:"btn btn-primary mt-2 mb-2" %>
</div>
<% end %>

app/views/roles/edit.html.erb
<h1>Edit Role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path, class:"btn btn-success" %>

app/views/roles/index.html.erb
  <%= link_to 'New role', new_role_path, class: "btn btn-danger", style: 'color:white' %>
<table>
 <thead>
  <tr>
    <th>Role name</th>
  </tr>
 </thead>

 <tbody>
  <% @roles.each do |role| %>
   <tr>
   	 <td><%= role.role_name %></td>
     <td><%= link_to 'Show', role_path(role), class:"btn btn-dark pe-3" %> </td>        
     <td><%= link_to 'Edit', edit_role_path(role), class:"btn btn-dark pe-4" %> </td>               
     <td><%= button_to 'Destroy', role_path(role), class:"btn btn-dark",
          data: { confirm: "Are you sure?", turbo_confirm: "Are you sure?" },
          method: :delete %>                 
      </td>
   </tr>
  <% end %>
 </tbody>
</table>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path, class:"btn btn-success" %>

app/views/roles/show.html.erb
<body>
<strong class="fs-5">Role name:</strong>
<%= @role.role_name %></br>

<%= link_to 'Back', roles_path, class:"btn btn-success ms-4" %>
</body>