config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
   devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  
  devise_scope :user do
    post '/users/create', to: 'users#create', as: :create_user
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "blogs#index"
  resources :roles
  resources :blogs
  resources :users
end

app/views/layouts/_footer.html.erb
<div class="navbar navbar-sm navbar-footer border-top">
	<div class="container-fluid">
		<span>&copy; <%= Time.now.utc.year %></span>
		<%= link_to "Blog", root_path %>
	</div>
</div>

app/views/layouts/_main_navbar.html.erb
<div class="navbar navbar-dark navbar-expand-lg navbar-static border-bottom border-bottom-white border-opacity-10">
	<div class="container-fluid">
		<div class="d-flex d-lg-none me-2">
			<button type="button" class="navbar-toggler sidebar-mobile-main-toggle rounded-pill">
				<i class="ph-list"></i>
			</button>
		</div>
		<div class="navbar-brand flex-1 flex-lg-0">
			<a href="#" class="d-inline-flex align-items-center">
				<%= image_tag "logo_icon.svg", alt: "logo_icon.svg" %>
				<%= link_to "Blogs", root_path, class:"fs-5 fw-bold ps-3 text-white" %>
			</a>
		</div>
		<ul class="nav flex-row justify-content-end order-1 order-lg-2">
			<li class="nav-item nav-item-dropdown-lg dropdown ms-lg-2">
				<a href="#" class="navbar-nav-link align-items-center rounded-pill p-1" data-bs-toggle="dropdown">
					<div class="status-indicator-container">
						<%= image_tag "face11.jpg", class: "w-32px h-32px rounded-pill", alt: "face11.jpg" %>
						<span class="status-indicator bg-success"></span>
					</div>
					<span class="d-none d-lg-inline-block mx-lg-2"><%= current_user.first_name %><%= " "%><%= current_user.last_name %></span>
				</a>
				<div class="dropdown-menu dropdown-menu-end">
					<a href="#" class="dropdown-item">
						<%= link_to edit_user_registration_path, class:"text-black ps-3" do %>
                          <i class="ph-user-circle pe-2"></i>
                          My profile
                        <% end %>
					</a>

					<a href="#" class="dropdown-item">
						<%= link_to destroy_user_session_path, class:"text-black ps-3" do %>
                          <i class="ph-sign-out pe-2"></i>
                          Log out
                        <% end %>
					</a>
				</div>
		</ul>
	</div>
</div>

app/views/layouts/_main_sidebar.html.erb
<div class="sidebar sidebar-dark sidebar-main sidebar-expand-lg">
	<!-- Sidebar content -->
	<div class="sidebar-content">
		<!-- Sidebar header -->
		<div class="sidebar-section">
			<div class="sidebar-section-body d-flex justify-content-center">
				<h5 class="sidebar-resize-hide flex-grow-1 my-auto">Navigation</h5>
				<div>
					<button type="button" class="btn btn-flat-white btn-icon btn-sm rounded-pill border-transparent sidebar-control sidebar-main-resize d-none d-lg-inline-flex">
						<i class="ph-arrows-left-right"></i>
					</button>
					<button type="button" class="btn btn-flat-white btn-icon btn-sm rounded-pill border-transparent sidebar-mobile-main-toggle d-lg-none">
						<i class="ph-x"></i>
					</button>
				</div>
			</div>
		</div>
		<!-- /sidebar header -->
		<!-- Main navigation -->
		<div class="sidebar-section">
			<ul class="nav nav-sidebar" data-nav-type="accordion">
				<!-- Main -->
				<li class="nav-item-header pt-0">
					<div class="text-uppercase fs-sm lh-sm opacity-50 sidebar-resize-hide">Main</div>
					<i class="ph-dots-three sidebar-resize-show"></i>
				</li>
				<li class="nav-item">
				  <%= link_to '<i class="ph-house"></i> Blogs'.html_safe, blogs_path, class:"nav-link" %>
				</li>
				<li class="nav-item">
					<% if current_user.role.role_name == "admin" %>
					  <%= link_to '<i class="ph-layout"></i> Users'.html_safe, users_index_path, class:"nav-link" %>
					<% end %>
				</li>
				
				<!-- /main -->
			</ul>
		</div>
		<!-- /main navigation -->
	</div>
	<!-- /sidebar content -->
</div>

app/views/layouts/_navbar.html.erb
 <nav>
    <div class="navbar navbar-dark navbar-static py-2">
    <div class="container-fluid">
      <div class="navbar-brand d-inline-flex align-items-center">
           <%= image_tag src="logo_icon.svg" %>
          <%= link_to "Blogs", root_path, class:"fs-5 fw-bold ps-3 text-white" %>
      </div>

      <div class="d-flex justify-content-end align-items-center ms-auto">
        <ul class="navbar-nav flex-row">
          <% if user_signed_in? %>
            <%= link_to current_user.email, edit_user_registration_path, class:"d-none d-md-inline-block ms-2 text-white pe-3" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"d-none d-md-inline-block ms-2 text-white pe-3" %>
          <% else %>
           <div class="d-flex align-items-center mx-md-1">
            <i class="ph-user-circle"></i>
            <%= link_to "Log in", new_user_session_path, class:"d-none d-md-inline-block ms-2 text-white me-3" %>
           </div>
           <div class="d-flex align-items-center mx-md-1">
            <i class="ph-user-circle-plus"></i>
            <%= link_to "Register", new_user_registration_path, class:"d-none d-md-inline-block ms-2 pe-3 text-white" %>
           </div>
          <% end %>
        
        </ul>
      </div>
    </div>
  </div>
  </nav>
 

app/views/layouts/_page_header.html.erb
<div class="page-header page-header-light shadow">
	<div class="page-header-content d-lg-flex">
		<div class="d-flex">
			<h4 class="page-title mb-0">
				Tables - <span class="fw-normal">Blogs</span>
			</h4>
		</div>
		<div class="collapse d-lg-block my-lg-auto ms-lg-auto">
          <%= link_to 'New blog', new_blog_path, class: "btn btn-danger", style: 'color:white' %>
        </div>
	</div>
	<div class="page-header-content d-lg-flex border-top">
		<div class="d-flex">
			<div class="breadcrumb py-2">
				<a href="#" class="breadcrumb-item"><i class="ph-house"></i></a>
				<a href="#" class="breadcrumb-item">Blogs</a>
				<span class="breadcrumb-item active">Basic examples</span>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_user_page_header.html.erb
<div class="page-header page-header-light shadow">
	<div class="page-header-content d-lg-flex">
		<div class="d-flex">
			<h4 class="page-title mb-0">
				Tables - <span class="fw-normal">Users</span>
			</h4>
		</div>
		<div class="collapse d-lg-block my-lg-auto ms-lg-auto">
          <%= link_to 'New user', new_user_path, class: "btn btn-danger", style: 'color:white' %>
        </div>
	</div>
	<div class="page-header-content d-lg-flex border-top">
		<div class="d-flex">
			<div class="breadcrumb py-2">
				<span class="breadcrumb-item"><i class="ph-house"></i></span>
				<span class="breadcrumb-item">Users</span>
				<span class="breadcrumb-item active">Basic examples</span>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>BlogDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- Main navbar -->
    <%= render "layouts/main_navbar" %>
    <!-- /main navbar -->
    <!-- Page content -->
    <div class="page-content">
      <!-- Main sidebar -->
      <%= render "layouts/main_sidebar" %>
      <!-- /main sidebar -->
      <!-- Main content -->
      <div class="content-wrapper">
        <!-- Inner content -->
        <div class="content-inner">
          <!-- Page header -->
          <%= render "layouts/page_header" %>
          <!-- /page header -->
          <!-- Content area -->
          <div class="content">
          <% flash.each do |type, message| %>
            <div class="alert text-white alert-icon-start  <% if type == 'notice' %>bg-success<% else %>bg-danger<% end %> alert-dismissible fade show border-0" role="alert">
            <% if type == 'notice' %>
            <span class="alert-icon bg-black bg-opacity-20">
              <i class="ph-check-circle"></i>
            </span>
            <% else %>
             <span class="alert-icon bg-black bg-opacity-20">
                <i class="ph-x-circle"></i>
              </span>
             <% end %>
            <%= message %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
           </div>
          <% end %>
          <%= yield %>
          </div>
          <!-- /content area -->
          <!-- Footer -->
          <%= render "layouts/footer" %>
          <!-- /footer -->
        </div>
        <!-- /inner content -->
      </div>
      <!-- /main content -->
    </div>
    <!-- /page content -->
  </body>
</html>

app/views/layouts/sign_in.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Blogs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- Main navbar -->
    <%= render "layouts/navbar" %>
    <!-- /main navbar -->
    <!-- Page content -->
    <div class="page-content">
      <!-- Main sidebar -->
      <!-- /main sidebar -->
      <!-- Main content -->
      <div class="content-wrapper">
        <!-- Inner content -->
        <div class="content-inner">
          <!-- Page header -->
          <!-- /page header -->
          <!-- Content area -->
          <div class="content">
            <%= yield %>
          </div>
          <!-- /content area -->
          <!-- Footer -->
          <%= render "layouts/footer" %>
          <!-- /footer -->
        </div>
        <!-- /inner content -->
      </div>
      <!-- /main content -->
    </div>
    <!-- /page content -->
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>BlogDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- Main navbar -->
    <%= render "layouts/main_navbar" %>
    <!-- /main navbar -->
    <!-- Page content -->
    <div class="page-content">
      <!-- Main sidebar -->
      <%= render "layouts/main_sidebar" %>
      <!-- /main sidebar -->
      <!-- Main content -->
      <div class="content-wrapper">
        <!-- Inner content -->
        <div class="content-inner">
          <!-- Page header -->
          <%= render "layouts/user_page_header" %>
          <!-- /page header -->
          <!-- Content area -->
          <div class="content">
          <% flash.each do |type, message| %>
            <div class="alert text-white alert-icon-start  <% if type == 'notice' %>bg-success<% else %>bg-danger<% end %> alert-dismissible fade show border-0" role="alert">
            <% if type == 'notice' %>
            <span class="alert-icon bg-black bg-opacity-20">
              <i class="ph-check-circle"></i>
            </span>
            <% else %>
             <span class="alert-icon bg-black bg-opacity-20">
                <i class="ph-x-circle"></i>
              </span>
             <% end %>
            <%= message %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
           </div>
          <% end %>
          <%= yield %>
          </div>
          <!-- /content area -->
          <!-- Footer -->
          <%= render "layouts/footer" %>
          <!-- /footer -->
        </div>
        <!-- /inner content -->
      </div>
      <!-- /main content -->
    </div>
    <!-- /page content -->
  </body>
</html>